# Generated by Django 4.2.1 on 2023-07-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0003_alter_user_managers_remove_user_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administradoruser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='administradores', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='administradoruser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='administradores', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
