# Generated by Django 4.2.1 on 2023-07-25 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_bibliotecario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdministradorUser',
        ),
    ]
