# Generated by Django 4.2.1 on 2023-12-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_administradoruser'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubUserViewSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
