# Generated by Django 4.2.1 on 2024-09-07 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_provider_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
