# Generated by Django 4.2.1 on 2023-07-26 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_autor', models.CharField(max_length=250, verbose_name='Autor')),
            ],
            options={
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(max_length=50, verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_editora', models.CharField(max_length=250, verbose_name='Editora')),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_livro', models.CharField(max_length=100, verbose_name='Nome do Livro')),
                ('data_cadastro', models.DateField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_lancamento', models.DateField(verbose_name='Data de Lançamento')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('descricao_livro', models.TextField(blank=True, max_length=200, null=True, verbose_name='Descrição do Livro')),
                ('cover', models.ImageField(upload_to='')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livros.autor', verbose_name='Autor')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livros.categoria', verbose_name='Categoria')),
                ('editora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livros.editora', verbose_name='Editora')),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateField(auto_now_add=True, verbose_name='Data de Empréstimo')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livros.livro', verbose_name='Livro')),
                ('nome_emprestado_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Cadastrado')),
            ],
        ),
        migrations.CreateModel(
            name='Devolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_devolucao', models.DateField(verbose_name='Data de Devolução')),
                ('avaliacao', models.CharField(blank=True, choices=[('PESSIMO', 'Péssimo'), ('RUIM', 'Ruim'), ('BOM', 'Bom'), ('OTIMO', 'Ótimo')], max_length=10, null=True)),
                ('emprestimo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='livros.emprestimo', verbose_name='Livro')),
                ('usuario_devolucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Devolução')),
            ],
        ),
    ]
