# Generated by Django 4.2.1 on 2023-05-30 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_autor', models.CharField(max_length=250, verbose_name='Autor')),
            ],
            options={
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(max_length=50, verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_editora', models.CharField(max_length=250, verbose_name='Editora')),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_livro', models.CharField(max_length=100, verbose_name='Nome do Livro')),
                ('data_cadastro', models.DateField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_lancamento', models.DateField(verbose_name='Data de Lançamento')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('descricao_livro', models.TextField(max_length=200, verbose_name='Descrição do Livro')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livros.categoria', verbose_name='Categoria')),
                ('editora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livros.editora', verbose_name='Editora')),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_emprestado_usuario', models.CharField(max_length=150, verbose_name='Nome Usuário Cadastrado')),
                ('nome_emprestado_anonimo', models.CharField(max_length=150, verbose_name='Nome Usuário Anônimo')),
                ('data_emprestimo', models.DateField(verbose_name='Data de Empréstimo')),
                ('data_devolucao', models.DateField(verbose_name='Data de Devolução')),
                ('avaliacao', models.CharField(blank=True, choices=[('P', 'Péssimo'), ('R', 'Ruim'), ('B', 'Bom'), ('O', 'Ótimo')], max_length=1, null=True)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livros.livro', verbose_name='Livro')),
            ],
        ),
    ]
