# Generated by Django 4.2.1 on 2023-05-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_livro_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='descricao_livro',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Descrição do Livro'),
        ),
    ]
