# Generated by Django 4.2.1 on 2023-05-30 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0003_alter_livro_descricao_livro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateField(auto_now_add=True, verbose_name='Data de Empréstimo'),
        ),
    ]
