# Generated by Django 4.2.1 on 2023-05-27 17:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0003_alter_autor_options_alter_categoria_nome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_emprestado', models.CharField(max_length=255, verbose_name='Nome')),
                ('dataemprestimo', models.DateField(verbose_name='Data de Empréstimo')),
                ('datadevolucao', models.DateField(verbose_name='Data de Devolução')),
                ('avaliacao', models.CharField(blank=True, choices=[('P', 'Péssimo'), ('R', 'Ruim'), ('B', 'Bom'), ('O', 'Ótimo')], max_length=1, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='livro',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='datacadastro',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='datalancamento',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='editora',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='titulo',
        ),
        migrations.AddField(
            model_name='livro',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livro',
            name='nome',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='autor',
            name='nome',
            field=models.CharField(max_length=250, verbose_name='Autor'),
        ),
    ]
