# Generated by Django 4.2.1 on 2023-05-30 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0004_alter_emprestimo_data_emprestimo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='nome_emprestado_anonimo',
        ),
    ]
