# Generated by Django 4.2.1 on 2023-07-11 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('livros', '0006_alter_emprestimo_nome_emprestado_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='data_devolucao',
        ),
        migrations.CreateModel(
            name='Devolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_devolucao', models.DateField(verbose_name='Data de Devolução')),
                ('emprestimo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='livros.emprestimo', verbose_name='Empréstimo')),
                ('usuario_devolucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Devolução')),
            ],
        ),
    ]
