# Generated by Django 4.2.1 on 2023-07-11 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0007_remove_emprestimo_data_devolucao_devolucao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='avaliacao',
        ),
        migrations.AddField(
            model_name='devolucao',
            name='avaliacao',
            field=models.CharField(blank=True, choices=[('P', 'Péssimo'), ('R', 'Ruim'), ('B', 'Bom'), ('O', 'Ótimo')], max_length=1, null=True),
        ),
    ]
