# Generated by Django 4.2.1 on 2023-07-11 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0008_remove_emprestimo_avaliacao_devolucao_avaliacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devolucao',
            name='emprestimo',
        ),
        migrations.AddField(
            model_name='devolucao',
            name='livro',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='livros.emprestimo', verbose_name='Livro'),
            preserve_default=False,
        ),
    ]
