# Generated by Django 4.2.1 on 2023-07-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0009_remove_devolucao_emprestimo_devolucao_livro'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='status',
            field=models.CharField(default='Emprestado', max_length=20),
        ),
    ]
