# Generated by Django 4.2.1 on 2023-07-23 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0012_livro_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='status',
        ),
    ]
