# Generated by Django 4.2.1 on 2023-07-25 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('livros', '0014_remove_emprestimo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucao',
            name='usuario_devolucao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Devolução'),
            preserve_default=False,
        ),
    ]
