# Generated by Django 4.2.1 on 2023-07-25 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0015_devolucao_usuario_devolucao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devolucao',
            name='observacoes',
        ),
    ]
