# Generated by Django 4.2.1 on 2023-07-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0017_alter_devolucao_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucao',
            name='avaliacao',
            field=models.CharField(blank=True, choices=[('PESSIMO', 'Péssimo'), ('RUIM', 'Ruim'), ('BOM', 'Bom'), ('OTIMO', 'Ótimo')], max_length=10, null=True),
        ),
    ]
