# Generated by Django 4.2.1 on 2023-07-27 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0018_alter_devolucao_avaliacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devolucao',
            name='avaliacao',
        ),
    ]
