# Generated by Django 4.2.1 on 2024-07-09 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0019_remove_devolucao_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='cover',
            field=models.ImageField(upload_to='livros/cover/%Y/%m/%d/'),
        ),
    ]
