# Generated by Django 5.0 on 2024-09-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0020_alter_livro_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='instituicao',
            field=models.CharField(max_length=100, null=True, verbose_name='Instituição'),
        ),
    ]
