# Generated by Django 5.0 on 2024-09-09 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0021_livro_instituicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='categoria',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='livros.categoria', verbose_name='Categoria'),
        ),
    ]
