# Generated by Django 5.0 on 2024-09-09 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0022_alter_livro_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livros.categoria', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='descricao_livro',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Descrição do Livro'),
        ),
    ]
