# Generated by Django 5.0 on 2024-09-09 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0023_alter_livro_categoria_alter_livro_descricao_livro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='descricao_livro',
            field=models.TextField(blank=True, max_length=70, null=True, verbose_name='Descrição do Livro'),
        ),
    ]
